[package]
name = "kanye-rust"
description = "A random Kanye West quote generator"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/synthetic-borealis/kanye-rust/"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rand = "0.8.5"
