[package]
name = "kanye-rust"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
shuttle-service = { version = "0.5.2", features = ["web-rocket"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rand = "0.8.5"
